name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Packages
        run: sudo apt install ffmpeg unzip python3 -y && python3 -m pip install --upgrade pip && pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: install playerwright
        run: |
          python3 -m playwright install
          python3 -m playwright install-deps

      - name: git config
        run: |
          git config --global user.name "TerraPlayz"
          git config --global user.email "omsenjalia@gmail.com"
          git pull

      - name: get assets and needed files.
        run: |
         unzip assets.zip
         
      - name: run the program 
        run: |
         python3 main.py
         git lfs install
         git lfs track results/*/*
         git add results -f
         git add results/* -f
         git commit -m "add LFS"
         git push -f
         
      - name: pull latest files
        run: git pull -f
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update reddit videos
      - name: results delete 
        run: |
         rm -rf results/*
